pipeline:

  install:
    image: node:10
    commands:
      - npm install

  build:
    image: node:10
    commands:
      - npm run build
    when:
      event: [ push ]
      branch: [ master ]

  deploy:
    image: meltwaterfoundation/drone-serverless:1.27.2
    commands:
      - npm run deploy
    secrets:
      - aws_access_key_id
      - aws_secret_access_key
    when:
      event: [ push ]
      branch: [ master ]