---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mission Life Video Messaging Bucket
Resources:

  MissionLifeVideoMessagingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: app.missionlifechange.org
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - GET
            AllowedOrigins:
              - "*"
            MaxAge: 900